---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments
baseurl: /landing-page


### content configuration ###
title:       "Code Club Aotearoa - Landing Page"
keywords:    "CodeClub, code club, Aotearoa, New Zealand, IoT, Education, Tech, IT"
description: "Code Club Aotearoa - A nationwide learning network for kids!"
source_link: "https://github.com/codeclubnz/landing-page/"
favicon:     "img/favicon.ico"
touch_icon:  "img/logo-large.png"
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  grey:      '#666666'
  brand:     '#37bdb8'

kramdown:
  auto_ids:  false

